// Generated by Force10
// Do not edit this file manually.

export default {
  routes: [
    {
      pattern: '/',
      component: 'Home',
      middleware: ['web'],
      parameters: [],
    },
    {
      pattern: '/about',
      component: 'About',
      middleware: ['web'],
      parameters: [],
    },
    {
      pattern: '/users',
      component: 'Users/Index',
      middleware: ['web'],
      parameters: [],
    },
    {
      pattern: '/users/:user',
      component: 'Users/Show',
      middleware: ['web'],
      parameters: [{ name: 'user', required: true }],
    }
  ],
};